#!/bin/bash
GITROOT_DIR=$(dirname $(PWD))

alias le='cd $GITROOTDIR/leetcode'
alias ml='cd $GITROOTDIR/machinelearning'
alias in='cd $GITROOTDIR/interview'
alias sc='cd $GITROOTDIR/scala'
alias myl='cd $GITROOTDIR/myreference'
